name: CI

on:
  push: {}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: sudo chmod +x ci/checks.sh
      - run: ci/checks.sh
